### ISSUE TITLE
Get an error "Too long page number string"

### ISSUE THREAD

**Issue by Nyoho** [kmuto/review-index-sample#1]
このリポジトリの方法で索引をEPUBに入れる方法を試しています。

upmendex が `Too long page number string "0000†indextest.xhtml#_RVIDX_0000".` というエラーを出し、失敗します。

@kmuto さんはどのような環境で作られているでしょうか?

## 環境

試した環境です。

- ruby 3.1.2p20 (2022-04-12 revision 4491bb740a) [arm64-darwin21]
- review 5.6.0
- upmendex version 1.00 [ICU 70.1] (TeX Live 2022).
- mecab (gem) 0.996
- mecab (コマンド) 0.996 (Homebrew ARM)

## How to reproduce

`rake epub` する。

(出力の下の方)
```
upmendex: Not writing to /var/folders/f4/jfrxy6395c32wn9lxj58msv80000gn/T/book-epub-20221110-835-109il0/_RVIDX_index.ilg (openout_any = p).
This is upmendex version 1.00 [ICU 70.1] (TeX Live 2022).
Scanning style file /Users/nyoho/prog/ReViewStudy/review-index-sample/mendex_html.ist....done.
Scanning input file /var/folders/f4/jfrxy6395c32wn9lxj58msv80000gn/T/book-epub-20221110-835-109il0/_RVIDX_index.tex.
Too long page number string "0000†indextest.xhtml#_RVIDX_0000".
/myhomedirectory/prog/ReViewStudy/review-index-sample/hook_afterbackmatter_common.rb:121:in `main': 索引作成に失敗 (おそらく
  書読み失敗) (RuntimeError)
        from /Users/nyoho/prog/ReViewStudy/review-index-sample/hook_afterbackmatter.rb:7:in `<main>'
✔ SUCCESS built book.epub
```

`/var/folders/f4/jfrxy6395c32wn9lxj58msv80000gn/T/book-epub-20221110-835-109il0/_RVIDX_index.tex` はできているが、中が

```
\indexentry{さくいん@索引}{0008†index2.xhtml#_RVIDX_0008}
```
のように
ページ番号文字列として `0008†index2.xhtml#_RVIDX_0008` という長い文字列が使われている。

upmendex のソースコードによると 
https://github.com/TeX-Live/texlive-source/blob/1d4d3373fd4e4e7f13506b5f9d8b8ce41d44dcd4/texk/upmendex/fread.c#L525-L528 となっていて、15文字未満のページ番号文字列はエラーとなっているのではないかと思います。

**Comment by kmuto** [comment]
2021.9.18のupmendexのコミットで15文字以上の拒否になったのですね。手元はupmendex 0.54 TeXLive 2020バージョンでまだこのチェックが入る前だったので動いていたようです。mendexにも同じチェックロジックが入っているので、古いupmendexを持ってくる以外、当面の回避方法がないですね…。

**Comment by kmuto** [comment]
左右の番号は同じ・xhtmlは省略できる からソート時点では短くできそうな気がしますね。ちょっと実装してみます。

**Comment by Nyoho** [comment]
あ、本当ですね、少し前までのupmendexではこれは大丈夫だったんですね。(確かに本来のページ番号としては十分……)

短くする実装、ありがとうございます。僕も考えてみます。

**Comment by kmuto** [comment]
PR #2 で実装してmergeしてみました。
upmendexに通すときには `ドキュメント番号3桁_索引番号4桁` としておき、索引HTMLを作るときにファイル名に戻すというトリックです。
catalog情報をもとにしたシーケンシャルのドキュメント番号を保持するため、`_RVIDX_store.pstore`という一時ファイルを作っています。ちゃんとやるならrakeルールかhookで消すところですが、とりあえずサンプルとしてはこれでも問題ないかと思います。

**Comment by Nyoho** [comment]
ありがとうございます。この方法だと8桁になるわけですね。
実行してみました。.pstore ファイルも、索引も正常に作成されました。
.pstoreファイルはうまく消してみます。
ありがとうございました。
